/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lapack_JNIJava */

#ifndef _Included_lapack_JNIJava
#define _Included_lapack_JNIJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lapack_JNIJava
 * Method:    sumsquaredc
 * Signature: ([I[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_lapack_JNIJava_sumsquaredc
  (JNIEnv *, jobject, jintArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
