/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fftw_fftw */

#ifndef _Included_fftw_fftw
#define _Included_fftw_fftw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fftw_fftw
 * Method:    fftw
 * Signature: ([I[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_fftw_fftw_fftw
  (JNIEnv *, jclass, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
