/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

/* Header for class JNIJava */

#ifndef _Included_JNIJava
#define _Included_JNIJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIJava
 * Method:    printString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNIJava_printString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNIJava
 * Method:    average
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_JNIJava_average
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
